Update de.json
DeFiCh/app pull request #271
Opened 2021-01-12 19:41 UTC by thunderstorm99

fixed some German translation errors

2021-01-15 07:55 UTC, adrian-schnell approved these changes

2021-01-17 09:07 UTC, sergejmueller requested changes

2021-01-17 09:07 UTC, sergejmueller commented on webapp/src/translations/languages/de.json
> +        "receiveDFITitle": "DFI empfangen– DeFi app",
DFI empfangen

Based on https://github.com/DeFiCh/app/blob/master/webapp/src/translations/languages/en.json#L626

2021-01-17 09:17 UTC, sergejmueller commented
@thunderstorm99 
Can you pls use the current [en.json file](https://github.com/DeFiCh/app/blob/master/webapp/src/translations/languages/en.json) (there are new language idents added) as draft for your translations to avoid merge conflicts. Thanks.

2021-01-22 07:58 UTC, merged