Wallet drop
DeFiCh/app pull request #403
Opened 2021-01-27 06:13 UTC by monstrobishi

- Added functionality to add wallet manually.

2021-01-27 08:16 UTC, monstrobishi commented
@Sumit570 

while we're at it, can we rename "Wallets" in the side bar to "Balances", and change the + button to say "+ ADD BALANCE"

2021-01-27 08:17 UTC, monstrobishi commented
Also the title at the top "Wallets" -> "Balances"

2021-01-29 00:19 UTC, thedoublejay requested changes

2021-01-29 00:19 UTC, thedoublejay commented on webapp/src/containers/WalletPage/components/Tokens/TokensList/index.tsx
> +      .filter((t: IToken) => t.hash != '0');
You can replace the '0' with DFI_SYMBOL

2021-01-29 00:19 UTC, thedoublejay commented on webapp/src/containers/WalletPage/service.tsx
> +  const networkType = getNetworkType();
I think we can create a common method for these two lines. It's been used for the other methods as well.

2021-01-29 00:19 UTC, thedoublejay commented on webapp/src/containers/WalletPage/components/Tokens/TokensList/index.tsx
> +    return diffreneceArray.length > 1 ? true : false;
No need for true/false here. diffreneceArray.length > 1 would return boolean result. Minor typo on diffreneceArray  -> difference

2021-02-16 02:00 UTC, thedoublejay requested changes

2021-02-17 11:33 UTC, thedoublejay submitted a review, later dismissed

2021-03-11 08:08 UTC, monstrobishi commented
@thedoublejay can you check if this is good to merge?

2021-03-11 08:28 UTC, thedoublejay approved these changes

2021-03-11 08:28 UTC, merged