Design: update design of settings page
DeFiCh/app pull request #638
Opened 2021-03-11 14:18 UTC by fullstackninja864

- Change active color of general tab to green
- Move header nav buttons to match toggle button and input fields

2021-03-12 00:07 UTC, thedoublejay requested changes

2021-03-12 00:07 UTC, thedoublejay commented on webapp/src/containers/SettingsPage/components/SettingsTabHeader/SettingsTabHeader.module.scss
> +@import '~bootstrap/scss/functions';
use common.scss here

2021-03-17 00:43 UTC, thedoublejay submitted a review, later dismissed

2021-03-17 01:05 UTC, thedoublejay approved these changes

2021-03-17 01:49 UTC, fuxingloh approved these changes

2021-03-17 01:53 UTC, merged