Feature/hide consolidate utxos
DeFiCh/app pull request #660
Opened 2021-03-16 13:22 UTC by saurabh391

#### What kind of PR is this?:
Hide consolidate UTXOs option #469

/kind feature

#### What this PR does / why we need it:
This is PR is for the new settings design and countdown management feature.

#### Which issue(s) does this PR fixes?:
Hide consolidate UTXOs option #469

Fixes #

#### Additional comments?:

2021-03-17 00:31 UTC, thedoublejay commented
Let's include this on next release

2021-03-17 05:05 UTC, izzycsy commented
<img width="1018" alt="210317 v2 3 2 MN Settings - Blank" src="https://user-images.githubusercontent.com/65014479/111417686-57b3be00-8721-11eb-82db-25b881315ee6.png">

Hi @saurabh391 , settings page is blank. 
[Marvel ref](urlhttps://marvel-live.freetls.fastly.net/serve/2021/2/90c93752e834dcfbb7975bbe48d9c52.png?qual[…]y=95&fake=.png&width=320&crop=&dpr=1.7999999523162842)

2021-03-17 06:24 UTC, saurabh391 commented
> <img alt="210317 v2 3 2 MN Settings - Blank" width="1018" src="https://user-images.githubusercontent.com/65014479/111417686-57b3be00-8721-11eb-82db-25b881315ee6.png">
> 
> Hi @saurabh391 , settings page is blank.
> Marvel ref
I have hide security tab can you please test now @izzycsy

2021-03-17 10:46 UTC, thedoublejay requested changes

2021-03-17 10:46 UTC, thedoublejay commented on webapp/src/containers/SettingsPage/components/SettingsTabHeader/index.tsx
> +        {/* {displaySecurityTab && (
why was this removed?

2021-03-17 10:46 UTC, thedoublejay commented on webapp/src/containers/SettingsPage/index.tsx
> -          {props.isWalletCreatedFlag && props.isWalletEncrypted && (
same

2021-03-17 10:46 UTC, thedoublejay commented on webapp/src/containers/SettingsPage/saga.tsx
> +      if (
I suggest we use wallet_map.json instead of Persistent Store

2021-03-17 10:46 UTC, thedoublejay commented
@saurabh391  why did you comment out security tab?

2021-03-17 11:24 UTC, saurabh391 commented
> @saurabh391 why did you comment out the security tab?

@monstrobishi asked me to hide the security tab for now.

2021-03-17 11:25 UTC, thedoublejay commented
> > @saurabh391 why did you comment out the security tab?
> 
> @monstrobishi asked me to hide the security tab for now.

@monstrobishi Any reason why? It's the only place where you can change passphrase and lock timeout.

2021-03-17 11:29 UTC, monstrobishi commented
I was under the impression it hasn't been implemented yet?

2021-03-17 11:30 UTC, thedoublejay commented
> I was under the impression it hasn't been implemented yet?

Oh it's already implemented now. Users can change passphrase and update the auto lock

2021-03-17 11:32 UTC, monstrobishi commented
Ok right then we should keep it @saurabh391 , I misunderstood your question that time you asked, I thought it's a new feature

2021-03-17 11:33 UTC, saurabh391 commented
> > I was under the impression it hasn't been implemented yet?
> 
> Oh it's already implemented now. Users can change passphrase and update the auto lock

I was facing some issues with already implemented logic can you please check.

2021-03-17 11:33 UTC, saurabh391 commented
> Ok right then we should keep it @saurabh391 , I misunderstood your question that time you asked, I thought it's a new feature

No worries

2021-03-17 11:39 UTC, thedoublejay commented
> > > I was under the impression it hasn't been implemented yet?
> > 
> > 
> > Oh it's already implemented now. Users can change passphrase and update the auto lock
> 
> I was facing some issues with already implemented logic can you please check.

What issue?

2021-03-17 12:28 UTC, saurabh391 commented
> > > > I was under the impression it hasn't been implemented yet?
> > > 
> > > 
> > > Oh it's already implemented now. Users can change passphrase and update the auto-lock
> > 
> > 
> > I was facing some issues with already implemented logic can you please check.
> 
> What issue? pm

I have made the changes and unhide the tab.

2021-03-22 15:09 UTC, thedoublejay approved these changes

2021-03-22 15:09 UTC, merged